server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #u update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 607758489218-ei1abvrfdhq6stq9vc57t2mt4rem88pq.apps.googleusercontent.com
            client-secret: kt3C_uXLeeVq16CYmN90vFvh
            scope:
            - email
            - profile
       
          facebook:
            client-id: 844250392776196
            client-secret: 0e1cd864702ecf907cb92dc5723fe4eb
            scope:
            - email
            - public_profile
             
          naver:
            client-id: bKo6hP3kFxpFViq7lZAa
            client-secret: CTT3M9yrvj
            scope:
            - email
            - public_profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
            
            
            
            
            
            